name: test

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Execute tests (Unit and Feature tests) via PHPUnit   
      run: vendor/bin/phpunit --coverage-clover coverage.xml
    - name: Upload reports to codecov
      run: |
        export CODECOV_TOKEN="${{ secrets.CODECOV_TOKEN }}"
        bash <(curl -s https://codecov.io/bash)